/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cuadro.h"

bool_t
xdr_param (XDR *xdrs, param *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dato1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dato2))
		 return FALSE;
	return TRUE;
}
