/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CUADRO_H_RPCGEN
#define _CUADRO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param {
	int dato1;
	int dato2;
};
typedef struct param param;

#define CUADRO_PROG 2
#define CUADRO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PERIMETRO 1
extern  int * perimetro_1(int *, CLIENT *);
extern  int * perimetro_1_svc(int *, struct svc_req *);
#define AREA 2
extern  double * area_1(int *, CLIENT *);
extern  double * area_1_svc(int *, struct svc_req *);
extern int cuadro_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PERIMETRO 1
extern  int * perimetro_1();
extern  int * perimetro_1_svc();
#define AREA 2
extern  double * area_1();
extern  double * area_1_svc();
extern int cuadro_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CUADRO_H_RPCGEN */
